apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: llm-building-block
  title: LLM Building Block
  description: Deploy a preconfigured LLM microservice and publish to GitHub
spec:
  owner: building-blocks-team
  type: service

  #############################################
  # 1) Parameters users fill in the UI
  #############################################
  parameters:
    - title: LLM Configuration
      required: [serviceId, modelName]
      properties:
        serviceId:
          type: string
          title: Service ID (technical name)
          pattern: "^[a-z0-9-]+$"
        modelName:
          type: string
          title: Model name (e.g., gpt-4o-mini)
        temperature:
          type: number
          title: Model temperature
          default: 0.7
        maxTokens:
          type: integer
          title: Max Tokens
          default: 512

    - title: GitHub Repository Info
      required: [owner, repo, visibility, githubToken]
      properties:
        owner:
          type: string
          title: GitHub owner (username or org)
        repo:
          type: string
          title: Repository name
        visibility:
          type: string
          enum: [public, private, internal]
        githubToken:
          type: string
          title: GitHub Personal Access Token
          description: "Enter your GitHub PAT with repo permissions"
          ui:widget: password

  #############################################
  # 2) Steps
  #############################################
  steps:
    - id: fetch
      name: Fetch LLM Skeleton
      action: fetch:template
      input:
        url: ./skeletons
        targetPath: ./
        values:
          serviceId: ${{ parameters.serviceId }}
          modelName: ${{ parameters.modelName }}
          temperature: ${{ parameters.temperature }}
          maxTokens: ${{ parameters.maxTokens }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        description: "LLM Building Block for service ${{ parameters.serviceId }}"
        repoVisibility: ${{ parameters.visibility }}
        defaultBranch: main
        token: ${{ parameters.githubToken }}

    - id: register
      name: Register in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /llm-service/catalog-info.yaml

  #############################################
  # 3) Output
  #############################################
  output:
    links:
      - title: LLM Repository
        url: ${{ steps.publish.output.remoteUrl }}
