apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.componentName }}
  description: "Python LLM service"
spec:
  type: service
  lifecycle: experimental
  owner: platform-team