apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: llm-service
  title: LLM Service
  description: Create a new Python-based LLM service
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Component Info
      required:
        - componentName
      properties:
        componentName:
          type: string
          title: Component Name
          description: Name of the service

    - title: Model Configuration
      required:
        - openAiKey
      properties:
        openAiKey:
          type: string
          title: OpenAI Key
          description: API key for OpenAI

    - title: Destination
      required:
        - repoUrl
      properties:
        repoUrl:
          type: string
          title: Git Repository URL
          description: Where should the component be created?

  steps:
    - id: fetch
      name: Fetch Template Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          componentName: ${{ parameters.componentName }}
          openAiKey: ${{ parameters.openAiKey }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: "Generated Python LLM service"

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}